seed: 111
env_init_seed: 1
eval_init_seed: 2

num_train_steps: 200
num_envs: 3

environment:
  num_leaves: 11
  num_admx_nodes: 10

policy:
  hidden_size: 128
  depth: 2
  entropy_coef: 0.01
  baseline_momentum: 0.1

optimizer:
  learning_rate: 0.001

reward:
  snp_path: allele_counts.txt

logging:
  tqdm_print_rate: 100
